import type { AestheticMovement } from '@/types/analysis'

export const aestheticMovements: AestheticMovement[] = [
  {
    id: 'bauhaus',
    name: '包豪斯',
    nameEn: 'Bauhaus',
    era: '1919–1933',
    origin: '德国魏玛',
    philosophy: '形式追随功能。摒弃无谓的装饰，将艺术、工艺与技术统一，追求理性之美与大众可及的设计。',
    representatives: ['Walter Gropius', 'Ludwig Mies van der Rohe', 'Marcel Breuer', 'Wassily Kandinsky'],
    principles: ['功能决定形式', '几何抽象语言', '原色与黑白体系', '工业化批量生产'],
    matchedTags: ['高对比度', '水平构图', '垂直构图', '对称构图'],
    accentColor: '#D4372C',
  },
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    nameEn: 'Cyberpunk',
    era: '1980s–至今',
    origin: '科幻文学与日本动漫',
    philosophy: '高科技，低生活。在数字废墟与霓虹裂缝中审视技术异化，以反乌托邦的视觉语言抵抗同质化的未来。',
    representatives: ['William Gibson', 'Ridley Scott', 'Masamune Shirow', 'Syd Mead'],
    principles: ['霓虹冷光与深暗底色', '高饱和度对比', '像素化与故障美学', '有机与机械的融合'],
    matchedTags: ['高对比度', '多彩', '暗沉', '动态构图'],
    accentColor: '#00FFCC',
  },
  {
    id: 'wabi-sabi',
    name: '侘寂',
    nameEn: 'Wabi-Sabi',
    era: '15世纪–至今',
    origin: '日本茶道文化',
    philosophy: '不完美之美。接纳时间与自然的侵蚀痕迹，在不完备、无常与未完成中发现深邃的宁静与温暖。',
    representatives: ['千利休', 'Sen no Rikyū', '本阿弥光悦', '杢野仁兵卫'],
    principles: ['留白与余韵', '自然材质与肌理', '不对称的均衡', '时间的痕迹（风化、裂痕）'],
    matchedTags: ['低饱和度', '柔和', '水平构图', '单色系'],
    accentColor: '#B5A18E',
  },
  {
    id: 'art-deco',
    name: '装饰艺术',
    nameEn: 'Art Deco',
    era: '1920s–1940s',
    origin: '法国巴黎',
    philosophy: '华丽即是力量。以精密的几何装饰歌颂现代工业与都市繁华，将奢华与秩序编织为视觉交响。',
    representatives: ['A.M. Cassandre', 'Tamara de Lempicka', 'Raymond Templier', 'Émile-Jacques Ruhlmann'],
    principles: ['放射状对称构图', '阶梯式线条与锯齿形', '金属光泽与宝石色调', '精密的几何装饰纹样'],
    matchedTags: ['高对比度', '对称构图', '多彩', '明亮'],
    accentColor: '#C9A84C',
  },
  {
    id: 'minimalism',
    name: '极简主义',
    nameEn: 'Minimalism',
    era: '1960s–至今',
    origin: '美国纽约',
    philosophy: '少即是多。通过极致的削减抵达本质，让每一个留存元素都承担最大的表达力，在空无中蕴含无限。',
    representatives: ['Donald Judd', 'Agnes Martin', 'Dieter Rams', 'Ludwig Mies van der Rohe'],
    principles: ['绝对减法原则', '网格与重复', '单一材质与纯色', '空间即内容'],
    matchedTags: ['单色系', '低饱和度', '对称构图', '明亮'],
    accentColor: '#E5E5E5',
  },
  {
    id: 'surrealism',
    name: '超现实主义',
    nameEn: 'Surrealism',
    era: '1920s–1960s',
    origin: '法国巴黎',
    philosophy: '超越理性的真实。在梦与醒的缝隙中释放潜意识的意象，以荒诞而精确的描绘揭示比现实更真实的内心图景。',
    representatives: ['Salvador Dalí', 'René Magritte', 'Max Ernst', 'Frida Kahlo'],
    principles: ['梦境逻辑', '出人意料的并置', '超精细的荒诞', '变形与流动的形态'],
    matchedTags: ['动态构图', '对角线构图', '多彩', '复古'],
    accentColor: '#6B4C9A',
  },
  {
    id: 'brutalism',
    name: '粗野主义',
    nameEn: 'Brutalism',
    era: '1950s–1970s',
    origin: '英国伦敦',
    philosophy: '诚实于材料。不掩饰、不粉饰，以混凝土的粗犷与结构的赤裸表达社会理想与建筑的真实性。',
    representatives: ['Le Corbusier', 'Alison & Peter Smithson', 'Paulo Mendes da Rocha', 'Tadao Ando'],
    principles: ['清水混凝土肌理', '巨量体块的并置', '结构外露即装饰', '粗犷的几何力量'],
    matchedTags: ['暗沉', '高对比度', '垂直构图', '低饱和度'],
    accentColor: '#7A7A7A',
  },
  {
    id: 'impressionism',
    name: '印象派',
    nameEn: 'Impressionism',
    era: '1860s–1880s',
    origin: '法国巴黎',
    philosophy: '光影即主体。放弃对轮廓的执念，用碎裂的色彩与颤动的笔触捕捉瞬息万变的光，让视觉回归感知的原点。',
    representatives: ['Claude Monet', 'Pierre-Auguste Renoir', 'Camille Pissarro', 'Berthe Morisot'],
    principles: ['碎笔触与色彩并置', '外光写生与瞬间光影', '淡化轮廓线', '补色对比的视觉振动'],
    matchedTags: ['柔和', '多彩', '暖色调', '动态构图'],
    accentColor: '#7AAD6F',
  },
  {
    id: 'de-stijl',
    name: '风格派',
    nameEn: 'De Stijl',
    era: '1917–1931',
    origin: '荷兰莱顿',
    philosophy: '纯粹关系的和谐。将视觉语言还原至最基本元素——直线、原色与无彩色，在严格的理性法则中寻求普遍的审美秩序。',
    representatives: ['Piet Mondrian', 'Gerrit Rietveld', 'Theo van Doesburg', 'Vilmos Huszár'],
    principles: ['水平线与垂直线', '红黄蓝三原色', '黑白的结构线', '非对称的均衡'],
    matchedTags: ['高对比度', '对称构图', '多彩', '水平构图'],
    accentColor: '#1C5DAB',
  },
  {
    id: 'vaporwave',
    name: '蒸汽波',
    nameEn: 'Vaporwave',
    era: '2010s–至今',
    origin: '互联网文化',
    philosophy: '怀旧作为批判。以消费主义的视觉残骸拼贴出消逝的乌托邦，在粉紫色的数字迷雾中追问进步的幻觉。',
    representatives: ['Macintosh Plus', 'Blank Banshee', 'Dan Lopatin', 'James Ferraro'],
    principles: ['粉紫渐变与大理石纹', '早期数字界面元素', '古典雕塑与热带植物', '低分辨率与降质美学'],
    matchedTags: ['柔和', '复古', '多彩', '暖色调'],
    accentColor: '#FF6AD5',
  },
]
